CATH:
  sample_class: CATH_Sample
  base_tag: cath_
  base_dir: /import/a12/users/nickc/updated_cath/
  save_dir: /net/scratch-sheldon/aguljas/mlcg_training_data/
  pdb_file: /import/a12/users/nickc/updated_cath/pdbs/{}_eq.pdb
  cg_atoms:
  - N
  - CA
  - CB
  - C
  - O
  embedding_dict: embedding_map_fivebead
  embedding_function: embedding_fivebead
  skip_residues:
  - ACE
  - NME
  use_terminal_embeddings: false
  mapping: slice_aggregate
  prior_tag: cgschnet
  batch_size: 100
