dataset_name: CATH
names:
  - 1b43A02
sample_loader: input_generator.CATH_loader
tag: cath_
raw_data_dir: /import/a12/users/nickc/updated_cath/
save_dir: /net/scratch-sheldon/aguljas/mlcg_training_data/
pdb_template_fn: /import/a12/users/nickc/updated_cath/pdbs/{}_eq.pdb
cg_atoms: ["N","CA","CB","C","O"]
embedding_map: input_generator.CGEmbeddingMapFiveBead
embedding_func: input_generator.embedding_fivebead
skip_residues: ["ACE", "NME"]
use_terminal_embeddings: false
cg_mapping_strategy: slice_aggregate
fit_parameters:
  batch_size: 1000
  stride: 100
prior_tag: cgschnet
prior_builders:
  - class_path: input_generator.Bonds
    init_args:
      name: bonds
      separate_termini: true
      nl_builder: 
          class_path: input_generator.StandardBonds
      prior_fit_fn: input_generator.fit_harmonic_from_potential_estimates
      n_bins: 100
      bmin: 1
      bmax: 5
  - class_path: input_generator.Angles
    init_args:
      name: angles
      separate_termini: true
      nl_builder: 
          class_path: input_generator.StandardAngles
      prior_fit_fn: input_generator.fit_harmonic_from_potential_estimates
      n_bins: 100
      bmin: -1
      bmax: 1



