dataset_name: CATH_test
names: [1b43A02]
tag: "cath_"
save_dir: /net/scratch-sheldon/aguljas/mlcg_training_data/test_pipeline/
prior_tag: cgschnet
prior_fn: /import/a12/users/aguljas/mlcg-playground/examples/full_prior_model_cgschnet.pt
batch_size: 100
device: cuda